// Vue/src/orig_App.vue
<template>
  <div>
    <DxPivotGrid
      :ref="pivotGridRefKey"
      :allow-sorting-by-summary="true"
      :allow-sorting="true"
      :allow-filtering="true"
      :allow-expand-all="true"
      :show-borders="true"
      :data-source="dataSource"
      @cell-click="onCellClick"
    >
      <DxFieldChooser :enabled="false" />
    </DxPivotGrid>
    <DxPopup
      :width="600"
      :height="400"
      :title.sync="popupTitle"
      :visible.sync="popupVisible"
      @showing="onShowing"
      @hiding="onHiding"
      @shown="onShown"
    >
      <DxDataGrid
        :ref="gridRefKey"
        :width="560"
        :height="300"
        @row-inserting="onRowInserting"
        @row-updating="onRowUpdating"
        @row-removing="onRowRemoving"
      >
        <DxEditing
          :allow-updating="true"
          :allow-deleting="true"
          :allow-adding="true"
        />

        <DxColumn data-field="region" />
        <DxColumn data-field="city" />
        <DxColumn data-field="amount" data-type="number" />
        <DxColumn data-field="date" data-type="date" />
      </DxDataGrid>
    </DxPopup>
  </div>
</template>
<script>
import DxPivotGrid, { DxFieldChooser } from "devextreme-vue/pivot-grid";
import { DxPopup } from "devextreme-vue/popup";
import { DxDataGrid, DxColumn, DxEditing } from "devextreme-vue/data-grid";

import PivotGridDataSource from "devextreme/ui/pivot_grid/data_source";
import ArrayStore from "devextreme/data/array_store";

import { sales } from "./data.js";

const pivotGridRefKey = "my-pivot-grid";
const gridRefKey = "my-grid";

export default {
  components: {
    DxPivotGrid,
    DxFieldChooser,
    DxPopup,
    DxDataGrid,
    DxColumn,
    DxEditing,
  },
  data() {
    return {
      pivotGridRefKey,
      gridRefKey,
      drillDownDataSource: {},
      data: new ArrayStore({
        data: sales,
        key: "id",
      }),
      dataSource: new PivotGridDataSource({
        fields: [
          {
            caption: "Region",
            width: 120,
            dataField: "region",
            area: "row",
          },
          {
            caption: "City",
            dataField: "city",
            width: 150,
            area: "row",
          },
          {
            dataField: "date",
            dataType: "date",
            area: "column",
          },
          {
            caption: "Total",
            dataField: "amount",
            dataType: "number",
            summaryType: "sum",
            format: "currency",
            area: "data",
          },
        ],
        store: sales,
      }),
      popupTitle: "",
      popupVisible: false,
    };
  },
  methods: {
    onCellClick(e) {
      if (e.area === "data") {
        var pivotGridDataSource = e.component.getDataSource(),
          rowPathLength = e.cell.rowPath.length,
          rowPathName = e.cell.rowPath[rowPathLength - 1],
          popupTitle =
            (rowPathName ? rowPathName : "Total") + " Drill Down Data";

        this.drillDownDataSource = pivotGridDataSource.createDrillDownDataSource(
          e.cell
        );

        this.popupTitle = popupTitle;
        this.popupVisible = true;
      }
    },
    onShowing() {
      var that = this;
      this.drillDownDataSource
        .store()
        .load()
        .done(function (items) {
          that.grid.option("dataSource", {
            store: new ArrayStore({
              key: that.data.key(),
              data: items,
            }),
          });
        });
    },
    onHiding() {
      this.pivotGrid.getDataSource().reload();
    },
    onShown() {
      this.grid.updateDimensions();
    },
    onRowInserting(e) {
      this.data.insert(e.data);
    },
    onRowUpdating(e) {
      this.data.update(e.key, e.newData);
    },
    onRowRemoving(e) {
      this.data.remove(e.key);
    },
  },
  computed: {
    pivotGrid: function () {
      return this.$refs[pivotGridRefKey].instance;
    },
    grid: function () {
      return this.$refs[gridRefKey].instance;
    },
  },
};
</script>
<style scoped>
#sales {
  margin: 20px 0;
}
</style>

// Angular/src/app/orig_app.component.ts
import { Component, ViewChild  } from '@angular/core';
import { DxDataGridComponent } from "devextreme-angular";
import PivotGridDataSource from 'devextreme/ui/pivot_grid/data_source';
import ArrayStore from 'devextreme/data/array_store';
import { Service, Sale } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
    @ViewChild("drillDownDataGrid", { static: false }) drillDownDataGrid: DxDataGridComponent
    sales: Sale[];
	data: ArrayStore;
    pivotGridDataSource: PivotGridDataSource;
    drillDownDataSource: any;
	dataGridDataSource: any;

    popupVisible = false;
    popupTitle: string;

    constructor(service: Service) {
        this.data = new ArrayStore({
            data: service.getSales(),
            key: "id"
        });
        
        this.pivotGridDataSource = new PivotGridDataSource({
            fields: [{
                caption: 'Region',
                width: 120,
                dataField: 'region',
                area: 'row'
            }, {
                caption: 'City',
                dataField: 'city',
                width: 150,
                area: 'row',
                selector: this.citySelector
            }, {
                dataField: 'date',
                dataType: 'date',
                area: 'column'
            }, {
                caption: 'Sales',
                dataField: 'amount',
                dataType: 'number',
                summaryType: 'sum',
                format: 'currency',
                area: 'data'
            }],
            store: this.data
        });
    }

    citySelector(data) {
        return data.city + ' (' + data.country + ')';
    }

    onCellClick(e) {
        if (e.area == "data") {
            var rowPathLength = e.cell.rowPath.length,
            rowPathName = e.cell.rowPath[rowPathLength - 1],
            popupTitle = (rowPathName ? rowPathName : "Total") + " Drill Down Data";

            this.drillDownDataSource = this.pivotGridDataSource.createDrillDownDataSource(
                e.cell
            );
            
            this.popupTitle = popupTitle;
            this.popupVisible = true;
        }
    }

	onPopupShowing(e) {
        var that = this;
        this.drillDownDataSource.store().load().done(function(items) {
			that.dataGridDataSource = {
                store: new ArrayStore({                     
                    key: that.data.key(),
                    data: items
                }) 
            };
        });
    }

	onPopupHiding(e) {
        this.pivotGridDataSource.reload();
    }

	onPopupShown(e) {
        this.drillDownDataGrid.instance.updateDimensions();
    }

	onRowUpdating(e) {
        this.data.update(e.key, e.newData);
    }

	onRowAdding(e) {
        this.data.insert(e.data);
    }

	onRowRemoving(e) {
        this.data.remove(e.key);
    }
}
<div class="long-title"><h3>Sales Amount by Region</h3></div>
<dx-pivot-grid id="sales"
  [allowSortingBySummary]="true"
  [allowSorting]="true"
  [allowFiltering]="true"
  [allowExpandAll]="true"
  [height]="440"
  [showBorders]="true"
  [dataSource]="pivotGridDataSource"
  (onCellClick)="onCellClick($event)">
  <dxo-export [enabled]="true" fileName="Sales"></dxo-export>
  <dxo-field-chooser [enabled]="false"></dxo-field-chooser>
</dx-pivot-grid>
<dx-popup
    [width]="600"
    [height]="400"
	[title]="popupTitle"
    [(visible)]="popupVisible"
    (onShowing)="onPopupShowing($event)"
	(onHiding)="onPopupHiding($event)"
	(onShown)="onPopupShown($event)">
    <div *dxTemplate="let data of 'content'">
        <dx-data-grid #drillDownDataGrid
            [dataSource]="dataGridDataSource"
            [showBorders]="true"
            [width]="560"
            [height]="300"
			(onRowUpdating)="onRowUpdating($event)"
            (onRowAdding)="onRowAdding($event)"
            (onRowRemoving)="onRowRemoving($event)">
            <dxo-editing
                [allowUpdating]="true"
                [allowAdding]="true"
                [allowDeleting]="true">
            </dxo-editing>
            <dxi-column dataField="region"></dxi-column>
            <dxi-column dataField="city"></dxi-column>
            <dxi-column dataField="amount" dataType="number"></dxi-column>
            <dxi-column dataField="date" dataType="date"></dxi-column>
        </dx-data-grid>
    </div>
</dx-popup>
